pipeline:
  run-test-suite:
    image: michalpodeszwa/docker-compose:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./bin/drone-run-tests.sh api-tests
    when:
      event: [pull_request]

  publish-api-docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    repo: paralect/ship-api
    tags:
      - latest
      - ${DRONE_BRANCH}
    dockerfile: ./api/Dockerfile
    context: ./api
    when:
      branch: ["master", "production"]
      event: [push]

  publish-web-docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    repo: paralect/ship-web
    tags:
      - latest
      - ${DRONE_BRANCH}
    dockerfile: ./web/Dockerfile
    context: ./web
    when:
      branch: ["master", "production"]
      event: [push]

  publish-landing-docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    repo: paralect/ship-landing
    tags:
      - latest
      - ${DRONE_BRANCH}
    dockerfile: ./landing/Dockerfile
    context: ./landing
    when:
      branch: ["master", "production"]
      event: [push]

  deploy-staging-app:
    image: williamyeh/ansible:ubuntu16.04
    secrets: [ ssh_key, docker_username, docker_password, docker_email ]
    commands:
      - mkdir -p ~/.ssh/
      - echo -n "$SSH_KEY" >> ~/.ssh/id_rsa_app && chmod 600 ~/.ssh/id_rsa_app
      - cp ./deploy/app/vars/credentials-template.yml ./deploy/app/vars/credentials.yml
      - cd ./deploy/app && ./bin/deploy-staging.sh --private-key ~/.ssh/id_rsa_app --extra-vars "docker_tag=latest docker_registry_username=$DOCKER_USERNAME docker_registry_password=$DOCKER_PASSWORD docker_registry_email=$DOCKER_EMAIL"
    when:
      branch: ["master"]
      event: [push]

branches: [ master, production, "*:master" ]
