---
- name: Setup server
  hosts: app
  become: true
  vars_files:
    - ["vars/main.yml"]
  roles:
    - { role: angstwad.docker_ubuntu}
  tasks:
    - name: Create base directories
      file: path="{{item}}" state=directory
      with_items:
        - "{{app_home}}"
        - "{{mongo_data_dir}}"
        - "{{redis_data_dir}}"
    
    - name: pull redis docker image
      docker_image:
        state: present
        force: yes
        name: "redis:4.0.8"
        tag: "4.0.8"
      tags:
        - redis

    - name: run redis using docker
      docker_container:
        name: redis
        image: redis:4.0.8
        command: ["redis-server", "--appendonly", "yes"]
        state: started
        restart_policy: always
        volumes:
          - "{{redis_data_dir}}:/data"
        ports:
          - "6379:6379"
      tags:
        - redis

    - name: pull mongo docker image
      docker_image:
        state: present
        force: yes
        name: "mongo:3.6.3"
        tag: "3.6.3"
      tags:
        - mongo

    - name: run mongo using docker
      docker_container:
        name: mongo
        image: mongo:3.6.3
        command: mongod
        state: started
        restart_policy: always
        volumes:
          - "{{mongo_data_dir}}:/data/db"
        ports:
          - "27017:27017"
      tags:
        - mongo
